### PR TITLE
Proposed solution to Issue #1071

### PR DESCRIPTION
**Pull request by hs-hub-world**
Please review. I have tested on my end works fine.
https://github.com/Squirrel/Squirrel.Windows/issues/1071

### CODE REVIEW

**Comment by hs-hub-world** [comment]
never mind.  there is something else. Debugging more...

**Comment by hs-hub-world** [comment]
False Alarm!  
The Proposed solution still remains valid. 
Please review and merge if you find it acceptable.  
I have successfully duplicated this issue on my end.

Thank you
H

**Comment by hs-hub-world** [comment]
Re-opening Pull request...

**Comment by hs-hub-world** [comment]
Any update on this request -?

Thanks!

**Comment by hs-hub-world** [comment]
ping  @paulcbetts

**Comment by paulcbetts** [comment]
I'm not super excited about this fix, though I think I get the idea of it

**Pull request closed without merging**
