### PR TITLE
added doc for migrating from ClickOnce to Squirrel

### PR DESCRIPTION
**Pull request by ghuntley**

### CODE REVIEW

**Comment by flagbug** [comment]
This works pretty well now btw

**Comment by theofanis** [comment]
@paulcbetts Any plans to include this in a near-future release?

**Comment by paulcbetts** [comment]
These are just docs, they're not really tied to a release

**Comment by theofanis** [comment]
Oops, just saw that, sorry, I thought it was an addition of flagbug's library.

**Comment by caveman-dick** [comment]
This pull request can be closed, there has been a large re-write of the docs and this is no longer required as it is in the FAQ's - https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/faq.md

**Pull request closed without merging**
