### PR TITLE
Reboot if necessary after .NET framework installation

### PR DESCRIPTION
**Pull request by willdean**
See #252 - this PR checks for the .NET framework installer return codes which indicate that a restart is required (without which the rest of the Squirrel install will fail).  

It then sets up a runonce entry to continue the installation after reboot, and does a reboot.   The installer will re-run after a reboot, and proceed as normal, because the framework is now available.

### CODE REVIEW

**Comment by willdean** [comment]
Possible issue with this is that if `isQuiet` is set, then this will reboot without asking permission.  Not sure if that's a good thing or not.

**Comment by paulcbetts** [comment]
> Possible issue with this is that if isQuiet is set, then this will reboot without asking permission. Not sure if that's a good thing or not.

That's a bad thing, we should print a "We have to reboot sry" message to stderr, then exit with a non-zero error code

**Comment by paulcbetts** [comment]
This is a great idea, thanks for the PR!

**Comment by willdean** [comment]
OK - I've made that change - PR's updated.  Just did a fprintf_s to stderr - not really sure if that's better or worse than OutputDebugString for a non-console app.

**Comment by paulcbetts** [comment]
I merged this with a few fixups, thanks!

**Comment by willdean** [comment]
I don't think 'well never get here because reboot' is right - the ExitWindowsEx call is async, and returns normally, even though a reboot has been scheduled - so I still think you want to treat this as some kind of blocking failure - perhaps using the same S_FALSE mechanism as for the message box?

**Comment by paulcbetts** [comment]
@willdean Fixed in 9e41fc3

**Pull request merged**
