### PR TITLE
FileDownloader constructor takes optional WebClient as a parameter

### PR DESCRIPTION
**Pull request by ionoy**
Makes it possible to provide custom Credentials and stuff

### CODE REVIEW

**Comment by paulcbetts** [comment]
Into it, but what's with all the whitespace changes?

**Comment by ionoy** [comment]
Method body was one tab to the left. I can revert if it was intentional.

**Comment by paulcbetts** [comment]
How in the world did that happen? Your version is definitely Better, merged!

**Comment by Thieum** [comment]
Does it handle the case where the url requires Authentication? That would be perfect for a use case I have :)

**Comment by grandtiger** [comment]
I ran into a use case where URL requires authentication. Is it possible to do? Thanks a lot!

**Comment by grandtiger** [comment]
@ionoy Hi Mihhail, how do you make use of this additional WebClient parameter? Is it possible to leverage this to handle URL requires authentication? Thanks!

**Pull request merged**
