### PR TITLE
Added additional shortcut location options

### PR DESCRIPTION
**Pull request by willdean**
Possible fix for #280

### CODE REVIEW

**Comment by jamesopti** [comment]
@willdean Is this still an issue? I'm looking for this workaround and am not sure if this is the only way!

**Comment by willdean** [comment]
@jamesopti I don't know - I just stuck in a PR against an issue which someone else had opened - neither the PR nor the issue have ever gone anywhere, and I don't know if the project has provided this functionality some other way.

**Comment by Thieum** [comment]
@shiftkey maybe this should be revived? It seems to adress a couple of issues.

**Comment by Thieum** [comment]
would fix #424 as well.

**Comment by shiftkey** [comment]
Let's talk about this more in #424, because if the escape hatch for making a custom shortcut isn't satisfactory we should figure out how to address that specific problem.

**Pull request closed without merging**
