### PR TITLE
Use GitHub url for UpdateManager

### LINKED ISSUE #223: UpdateManager CheckForUpdate from GitHub
Would it be worth including something similar to the GitHub implementation in SyncReleases in UpdateManager/CheckForUpdate methods?

### PR DESCRIPTION
**Pull request by BarryThePenguin**
closes #223

### CODE REVIEW

**Comment by paulcbetts** [comment]
Can you just use HttpClient instead of including Octokit? I'm trying to limit the dependencies of Squirrel.dll as much as possible

**Comment by BarryThePenguin** [comment]
I thought this functionality would fit better in squirrel because of the dependency. But I didn't think of httpclient.

Is the static class factory suitable? Or should I create a new factory class? Updatemanager is already quite large...

**Comment by BarryThePenguin** [comment]
Now using HttpClient and a custom Release object with relevant properties.

**Comment by BarryThePenguin** [comment]
A note on [HttpClient](http://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed)

**Comment by paulcbetts** [comment]
I'll have a look at this soon

**Comment by BarryThePenguin** [comment]
Heh... I just realised this doesn't support updates multiple and deltas...

**Comment by BarryThePenguin** [comment]
Although, during the update process, it did download both the new -full and -delta nupkg

**Comment by BarryThePenguin** [comment]
Any thoughts? Otherwise I'll just maintain this in the app

**Comment by paulcbetts** [comment]
Remember when I said I would look at this soon then _totally_ spaced on it? This time I'll actually look into it :)

**Comment by BarryThePenguin** [comment]
Sure, just looking for feedback. Would be good to know if this is a Good Idea™ or not ;)

**Comment by Cyral** [comment]
This is a great idea, I was about to suggest it myself because I needed it and then found this!

**Comment by paulcbetts** [comment]
:+1:

**Comment by ricardopolo** [comment]
So how to use it? 
It will download relases from Github Releases or what?

**Comment by BarryThePenguin** [comment]
Should this be documented? Where should the documentation be? Comments in code or a wiki page or similar?

**Comment by paulcbetts** [comment]
> Should this be documented? Where should the documentation be? Comments in code or a wiki page or similar?

Throw this up on a Wiki page if you would!

**Comment by BarryThePenguin** [comment]
I added it to the Client Implementation docs #391

**Pull request merged**
