### PR TITLE
Remove Splat External Dependency

### PR DESCRIPTION
**Pull request by nickhodge**
1. Take the 1.6.2 branch of [reactiveui/splat](https://github.com/reactiveui/splat/releases/tag/1.6.2)
2. Take the bare minimum required for Squirrel, change name space
3. Remove NuGet references to Splat
4. Correctly name things
5. Update to VS2019, Update GitVersioning

Tests ran 100% before and after this change.

### CODE REVIEW

**Comment by nickhodge** [comment]
hmm ... failing because VS2019 vs VS2017?

**Comment by anaisbetts** [comment]
I'll have a look at this soon

**Comment by samirem** [comment]
Waiting eagerly on this one, it would solve #1462 which has been blocking ReactiveUI users

**Comment by Hyrius** [comment]
Any update about this pull request?

**Comment by anaisbetts** [comment]
This is Very Much on my list, @nickhodge has done some awesome work here, sorry I'm dragging my feet.

**Comment by nickhodge** [comment]
I am Helping

**Comment by AppFzx** [comment]
Any update on status?

**Comment by guidovanhilst** [comment]
> Any update about this pull request?

I am having trouble using Squirrel.Windows and ReactiveUI due to error in Splat:

Exception in call to UpdateManager.UpdateApp():
"Method not found: 'Void Splat.IFullLogger.Info(System.String, !!0)'."

I am using the following nuget packages:
Splat 9.4.5.
ReactiveUI 9.19.5
Squirrel 1.9.1

I believe this commit solves the problem?
Is there going to be an update on www.nuget.org/packages/squirrel.windows?

Thanks, Guido

**Comment by wsaeed** [comment]
@anaisbetts What was the reason to revert back to VS 2017?

**Comment by ComtelJeremy** [comment]
@anaisbetts Any way this can get pushed to a release? We are unable to release our app's latest version since we now use the latest ReactiveUI... Pretty please?

**Pull request merged**
