### PR TITLE
Added docs for GitHub Implementation

### PR DESCRIPTION
**Pull request by BarryThePenguin**

### CODE REVIEW

**Comment by paulcbetts** [comment]
This should actually go somewhere in the docs folder, specs are more for historical design docs

**Comment by BarryThePenguin** [comment]
I'll fix this up when I'm on my desktop

**Comment by BarryThePenguin** [comment]
Finally got around to fixing this. It's now in the docs folder

**Comment by paulcbetts** [comment]
:+1: :sparkles:

**Pull request merged**
