### PR TITLE
Disable animated GIF window from showing up in the Taskbar

### PR DESCRIPTION
**Pull request by paulcbetts**
This PR removes the installation window from the Taskbar and makes it Always On Top for the first 5 seconds (then allows it to be backgrounded)

### CODE REVIEW

**Comment by 50Wliu** [comment]
Like you referenced in your commit, this literally removes the only gain that we got in #137.  At least with the taskbar window I could verify that it was still installing (and not crashed, frozen, etc.) by just glancing at the taskbar.  Now I have to minimize who knows how many windows just to get to the GIF (I minimize/maximize windows pretty often), then re-open them.

**Comment by paulcbetts** [comment]
>  Now I have to minimize who knows how many windows just to get to the GIF (I minimize/maximize windows pretty often), then re-open them.

The Window is now Always On Top for the first 5 seconds it exists, so this shouldn't be a problem

**Comment by 50Wliu** [comment]
Yes, but Atom takes more than 5 seconds to install.

**Comment by paulcbetts** [comment]
That's fine, after the 5 seconds is up people can put it to the background

**Comment by 50Wliu** [comment]
Yes, and that was fine when there was a taskbar icon, because I could bring it up again whenever I wanted to in order to check on it.  Now that's not possible.  Some people may infer that it just...disappeared (and/or crashed) after they get back to whatever they were working on before.

**Comment by paulcbetts** [comment]
Unless we get overwhelming feedback to the contrary during the Slack Windows beta that this is confusing users, this isn't going to change, sorry. I'm getting bugs internally from people who *don't* want  the icon in the taskbar - this is just a matter of personal taste or something.

**Comment by 50Wliu** [comment]
I guess so then.

**Pull request merged**
