### PR TITLE
Update SyncImplementations.cs

### PR DESCRIPTION
**Pull request by mbutters**
Update for SyncImplementations.cs to pass along query string parameters when requesting files. More info can be viewed at https://github.com/Squirrel/Squirrel.Windows/issues/769

### CODE REVIEW

**Comment by paulcbetts** [comment]
I'm into this as a concept, I'm just not sure it's correct

**Comment by mbutters** [comment]
Which part did you think is not correct?  The code change or something else?  FYI we did compile it on our end with the change and it did seem to work fine.  Our testing wasn't extensive but we were able to pass along query parameters and fetch what we were looking for.

**Comment by paulcbetts** [comment]
@mbutters How does this code build a correctly formatted URL just by concatenating?

**Comment by mbutters** [comment]
Although it is simple, the concatenation was following a similar pattern found here: 
https://github.com/Squirrel/Squirrel.Windows/blob/9de260cb6b614234511d57723738f1be2ed25476/src/Squirrel/UpdateManager.DownloadReleases.cs#L71

The query attribute is either [populated or null](https://github.com/Squirrel/Squirrel.Windows/blob/1aebe10db3e9d9b3d5a4c147622299d3a6073a30/src/Squirrel/ReleaseEntry.cs#L137).  In the case that it is null, C# will output it as an empty string.  When it is populated the query attribute of the Release Entry is pulled from the [Uri.Query](https://msdn.microsoft.com/en-us/library/system.uri.query(v=vs.110).aspx) attribute which will pull in the "?" and any key value pairs.  There are a few other ways of achieving the same results, however since the base url and file name were already being concatenated it seemed to make sense to also concatenate the query string to minimize the changes.

**Pull request merged**
