### PR TITLE
Preserve directories if squirrel aware exes are still running.

### PR DESCRIPTION
**Pull request by gajagt**
Fix for #646.

### CODE REVIEW

**Comment by gajagt** [comment]
@paulcbetts  Can you review this when you get a chance?

Thanks.

**Comment by gajagt** [comment]
Ping for @paulcbetts

**Comment by abhayketkar** [comment]
+1
@paulcbetts - I too am running into this issue.

**Comment by awedev** [comment]
+1, really need this. @paulcbetts

**Comment by sathya09** [comment]
I am running into this as well. Any timeline when a fix for this would be available?

**Comment by paulcbetts** [comment]
I fixed this a different way, thanks for the PR though!

**Comment by gajagt** [comment]
Thanks @paulcbetts ! When can we expect a release with this fix?

**Comment by paulcbetts** [comment]
Today

**Pull request closed without merging**
