### PR TITLE
Bugfix: Issue #288 DowloadReleases reports wrong progress

### PR DESCRIPTION
**Pull request by ogborstad**
I duplicated the logic from the production code into the test class to be able to test my code quickly.

### CODE REVIEW

**Comment by ogborstad** [comment]
I noticed @sickboy delivered a PR just about the same time as I did this. https://github.com/Squirrel/Squirrel.Windows/pull/297

@paulcbetts you can pick whatever implementation looks simplest

**Comment by paulcbetts** [comment]
I just hit merge on @sickboy's because he followed the coding style :)

**Comment by paulcbetts** [comment]
Thanks for having a look @ogborstad!

**Comment by ogborstad** [comment]
Thats fine, no problem!

**Pull request closed without merging**
